
package com.poc.soa.image.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Image", targetNamespace = "http://client.image.soa.poc.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Image {


    /**
     * 
     * @param putData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "putResponse", targetNamespace = "http://client.image.soa.poc.com")
    @RequestWrapper(localName = "put", targetNamespace = "http://client.image.soa.poc.com", className = "com.poc.soa.image.client.Put")
    @ResponseWrapper(localName = "putResponse", targetNamespace = "http://client.image.soa.poc.com", className = "com.poc.soa.image.client.PutResponse")
    public String put(
        @WebParam(name = "putData", targetNamespace = "http://client.image.soa.poc.com")
        byte[] putData);

}
