
package com.soacookbook.ns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Catalog", targetNamespace = "http://ns.soacookbook.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Catalog {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "title", targetNamespace = "")
    @RequestWrapper(localName = "getTitle", targetNamespace = "http://ns.soacookbook.com", className = "com.soacookbook.ns.GetTitle")
    @ResponseWrapper(localName = "getTitleResponse", targetNamespace = "http://ns.soacookbook.com", className = "com.soacookbook.ns.GetTitleResponse")
    public String getTitle(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
