
package com.soacookbook.ns;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatalogService", targetNamespace = "http://ns.soacookbook.com", wsdlLocation = "http://localhost:8080/soacookbook/CatalogService?wsdl")
public class CatalogService
    extends Service
{

    private final static URL CATALOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATALOGSERVICE_EXCEPTION;
    private final static QName CATALOGSERVICE_QNAME = new QName("http://ns.soacookbook.com", "CatalogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soacookbook/CatalogService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATALOGSERVICE_WSDL_LOCATION = url;
        CATALOGSERVICE_EXCEPTION = e;
    }

    public CatalogService() {
        super(__getWsdlLocation(), CATALOGSERVICE_QNAME);
    }

    public CatalogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATALOGSERVICE_QNAME, features);
    }

    public CatalogService(URL wsdlLocation) {
        super(wsdlLocation, CATALOGSERVICE_QNAME);
    }

    public CatalogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATALOGSERVICE_QNAME, features);
    }

    public CatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Catalog
     */
    @WebEndpoint(name = "CatalogPort")
    public Catalog getCatalogPort() {
        return super.getPort(new QName("http://ns.soacookbook.com", "CatalogPort"), Catalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Catalog
     */
    @WebEndpoint(name = "CatalogPort")
    public Catalog getCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.soacookbook.com", "CatalogPort"), Catalog.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATALOGSERVICE_EXCEPTION!= null) {
            throw CATALOGSERVICE_EXCEPTION;
        }
        return CATALOGSERVICE_WSDL_LOCATION;
    }

}
